language: python
python:
  - "2.7"
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - python -m nltk.downloader stopwords
  - python -m nltk.downloader universal_tagset
  - python -m spacy download en
script:
  - pytest